In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

X, y = make_classification(
    n_features=10, 
    n_samples=1000, 
    n_informative=8,
    n_redundant=2,
    n_repeated=0,
    n_classes=2, 
    random_state=42
)

### Method 01: Evaluate the model using train, test split and tune parameters by trail and error

In [6]:
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

model = DecisionTreeClassifier(criterion="gini", max_depth=10) # criteria: "gini" or "entropy", max_depth=5 or 10
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.83      0.85      0.84       130
           1       0.84      0.82      0.83       120

    accuracy                           0.84       250
   macro avg       0.84      0.84      0.84       250
weighted avg       0.84      0.84      0.84       250

### Method 2: Cross val score

In [9]:
from sklearn.model_selection import cross_val_score
model = DecisionTreeClassifier(criterion="gini", max_depth=5)
cross_val_scores = cross_val_score(model, X, y, cv=5)
print("Cross-validation scores:", cross_val_scores)
print("Average cross-validation score:", cross_val_scores.mean())

Cross-validation scores: [0.775 0.795 0.735 0.805 0.77 ]
Average cross-validation score: 0.776

In [10]:
from sklearn.model_selection import cross_val_score
model = DecisionTreeClassifier(criterion="gini", max_depth=10)
cross_val_scores = cross_val_score(model, X, y, cv=5)
print("Cross-validation scores:", cross_val_scores)
print("Average cross-validation score:", cross_val_scores.mean())

Cross-validation scores: [0.785 0.755 0.79  0.78  0.815]
Average cross-validation score: 0.785

In [11]:
from sklearn.model_selection import cross_val_score
model = DecisionTreeClassifier(criterion="entropy", max_depth=5)
cross_val_scores = cross_val_score(model, X, y, cv=5)
print("Cross-validation scores:", cross_val_scores)
print("Average cross-validation score:", cross_val_scores.mean())

Cross-validation scores: [0.765 0.775 0.755 0.815 0.78 ]
Average cross-validation score: 0.7779999999999999

In [13]:
criterion_options = ["gini", "entropy"]
max_depth_options = [5, 10, 15]
for criterion in criterion_options:
    for max_depth in max_depth_options:
        model = DecisionTreeClassifier(criterion=criterion, max_depth=max_depth)
        cross_val_scores = cross_val_score(model, X, y, cv=5)
        print(f"Criterion: {criterion}, Max Depth: {max_depth}")
        print("Cross-validation scores:", cross_val_scores)
        print("Average cross-validation score:", cross_val_scores.mean())
        print("-" * 50)

Criterion: gini, Max Depth: 5
Cross-validation scores: [0.775 0.81  0.73  0.79  0.775]
Average cross-validation score: 0.776
--------------------------------------------------
Criterion: gini, Max Depth: 10
Cross-validation scores: [0.765 0.725 0.795 0.79  0.82 ]
Average cross-validation score: 0.779
--------------------------------------------------
Criterion: gini, Max Depth: 15
Cross-validation scores: [0.81  0.725 0.815 0.795 0.815]
Average cross-validation score: 0.792
--------------------------------------------------
Criterion: entropy, Max Depth: 5
Cross-validation scores: [0.765 0.785 0.76  0.81  0.785]
Average cross-validation score: 0.781
--------------------------------------------------
Criterion: entropy, Max Depth: 10
Cross-validation scores: [0.77  0.77  0.81  0.785 0.785]
Average cross-validation score: 0.784
--------------------------------------------------
Criterion: entropy, Max Depth: 15
Cross-validation scores: [0.765 0.805 0.845 0.805 0.85 ]
Average cross-validation score: 0.8140000000000001
--------------------------------------------------

In [14]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [5, 10, 15]
}
grid_search = GridSearchCV(estimator=DecisionTreeClassifier(), param_grid=param_grid, cv=5, return_train_score=False)
grid_search.fit(X, y)
print("Best parameters:", grid_search.best_params_)

Best parameters: {'criterion': 'entropy', 'max_depth': 15}

In [16]:
df = pd.DataFrame(grid_search.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005075,0.000475,0.000783,0.000118,gini,5,"{'criterion': 'gini', 'max_depth': 5}",0.775,0.785,0.740,0.790,0.775,0.773,0.017493,6
1,0.011685,0.005462,0.001456,0.001018,gini,10,"{'criterion': 'gini', 'max_depth': 10}",0.810,0.750,0.815,0.795,0.815,0.797,0.024617,2
2,0.007464,0.000583,0.001626,0.001534,gini,15,"{'criterion': 'gini', 'max_depth': 15}",0.800,0.720,0.810,0.825,0.820,0.795,0.038471,3
3,0.008793,0.001959,0.000781,0.000221,entropy,5,"{'criterion': 'entropy', 'max_depth': 5}",0.765,0.775,0.755,0.810,0.780,0.777,0.018601,5
4,0.012081,0.001999,0.000820,0.000122,entropy,10,"{'criterion': 'entropy', 'max_depth': 10}",0.775,0.795,0.825,0.770,0.795,0.792,0.019391,4
5,0.013120,0.002672,0.000807,0.000147,entropy,15,"{'criterion': 'entropy', 'max_depth': 15}",0.760,0.795,0.830,0.805,0.870,0.812,0.036688,1

In [17]:
df[["param_criterion", "param_max_depth", "mean_test_score"]]

  param_criterion  param_max_depth  mean_test_score
0            gini                5            0.773
1            gini               10            0.797
2            gini               15            0.795
3         entropy                5            0.777
4         entropy               10            0.792
5         entropy               15            0.812

In [18]:
grid_search.best_estimator_

DecisionTreeClassifier(criterion='entropy', max_depth=15)

In [22]:
from sklearn import svm
mpdel_param = {
    'decision_tree': {
        'model': DecisionTreeClassifier(),
        'param_grid': {
            'criterion': ['gini', 'entropy'],
            'max_depth': [5, 10, 15]
        }
    },
    'SVM': {
        'model': svm.SVC(gamma='auto'),
        'param_grid': {
            'C': [1, 10, 20],
            'kernel': ['linear', 'rbf']
        }
    }
}

for model_name, mpdel_info in mpdel_param.items():
    print(f"Running GridSearchCV for {model_name}...")
    grid_search = GridSearchCV(estimator=mpdel_info['model'], param_grid=mpdel_info['param_grid'], cv=5, return_train_score=False)
    grid_search.fit(X, y)
    print(f"Best parameters for {model_name}: {grid_search.best_params_}")
    print("best score:", grid_search.best_score_)
    print("-" * 50)

Running GridSearchCV for decision_tree...
Best parameters for decision_tree: {'criterion': 'entropy', 'max_depth': 15}
best score: 0.817
--------------------------------------------------
Running GridSearchCV for SVM...
Best parameters for SVM: {'C': 1, 'kernel': 'rbf'}
best score: 0.9260000000000002
--------------------------------------------------